var searchData=
[
  ['basic_5fallocation_5finfo',['basic_allocation_info',['../classsequoia_1_1unit__testing_1_1basic__allocation__info.html',1,'sequoia::unit_testing']]],
  ['basic_5fallocation_5finfo_3c_20container_2c_20allocator_2c_20allocation_5fpredictions_20_3e',['basic_allocation_info&lt; Container, Allocator, allocation_predictions &gt;',['../classsequoia_1_1unit__testing_1_1basic__allocation__info.html',1,'sequoia::unit_testing']]],
  ['basic_5fallocation_5finfo_3c_20container_2c_20allocator_2c_20move_5fonly_5fallocation_5fpredictions_20_3e',['basic_allocation_info&lt; Container, Allocator, move_only_allocation_predictions &gt;',['../classsequoia_1_1unit__testing_1_1basic__allocation__info.html',1,'sequoia::unit_testing']]],
  ['basic_5fallocation_5finfo_3c_20container_2c_20std_3a_3ascoped_5fallocator_5fadaptor_3c_20allocators_2e_2e_2e_20_3e_2c_20predictions_20_3e',['basic_allocation_info&lt; Container, std::scoped_allocator_adaptor&lt; Allocators... &gt;, Predictions &gt;',['../classsequoia_1_1unit__testing_1_1basic__allocation__info_3_01_container_00_01std_1_1scoped__allob81d85e5047459e24719967088a72710.html',1,'sequoia::unit_testing']]],
  ['basic_5fgraph_5foperations',['basic_graph_operations',['../classsequoia_1_1unit__testing_1_1basic__graph__operations.html',1,'sequoia::unit_testing']]],
  ['basic_5fmove_5fonly_5fallocation_5ftest',['basic_move_only_allocation_test',['../classsequoia_1_1unit__testing_1_1basic__move__only__allocation__test.html',1,'sequoia::unit_testing']]],
  ['basic_5fregular_5fallocation_5ftest',['basic_regular_allocation_test',['../classsequoia_1_1unit__testing_1_1basic__regular__allocation__test.html',1,'sequoia::unit_testing']]],
  ['basic_5ftest',['basic_test',['../classsequoia_1_1unit__testing_1_1basic__test.html',1,'sequoia::unit_testing']]],
  ['basic_5ftest_3c_20checker_3c_20mode_2c_20move_5fonly_5fallocation_5fextender_3c_20mode_20_3e_20_3e_20_3e',['basic_test&lt; checker&lt; Mode, move_only_allocation_extender&lt; Mode &gt; &gt; &gt;',['../classsequoia_1_1unit__testing_1_1basic__test.html',1,'sequoia::unit_testing']]],
  ['basic_5ftest_3c_20checker_3c_20mode_2c_20regular_5fallocation_5fextender_3c_20mode_20_3e_20_3e_20_3e',['basic_test&lt; checker&lt; Mode, regular_allocation_extender&lt; Mode &gt; &gt; &gt;',['../classsequoia_1_1unit__testing_1_1basic__test.html',1,'sequoia::unit_testing']]],
  ['basic_5ftest_3c_20graph_5fchecker_3c_20mode_2c_20extenders_2e_2e_2e_20_3e_20_3e',['basic_test&lt; graph_checker&lt; Mode, Extenders... &gt; &gt;',['../classsequoia_1_1unit__testing_1_1basic__test.html',1,'sequoia::unit_testing']]],
  ['bfs',['BFS',['../structsequoia_1_1unit__testing_1_1_b_f_s.html',1,'sequoia::unit_testing']]],
  ['big_5funsortable',['big_unsortable',['../structsequoia_1_1unit__testing_1_1big__unsortable.html',1,'sequoia::unit_testing']]],
  ['broken_5fcopy',['broken_copy',['../structsequoia_1_1unit__testing_1_1broken__copy.html',1,'sequoia::unit_testing']]],
  ['broken_5fcopy_5falloc',['broken_copy_alloc',['../structsequoia_1_1unit__testing_1_1broken__copy__alloc.html',1,'sequoia::unit_testing']]],
  ['broken_5fcopy_5fassignment',['broken_copy_assignment',['../structsequoia_1_1unit__testing_1_1broken__copy__assignment.html',1,'sequoia::unit_testing']]],
  ['broken_5fcopy_5fassignment_5fvalue_5fsemantics',['broken_copy_assignment_value_semantics',['../structsequoia_1_1unit__testing_1_1broken__copy__assignment__value__semantics.html',1,'sequoia::unit_testing']]],
  ['broken_5fcopy_5fvalue_5fsemantics',['broken_copy_value_semantics',['../structsequoia_1_1unit__testing_1_1broken__copy__value__semantics.html',1,'sequoia::unit_testing']]],
  ['broken_5fequality',['broken_equality',['../structsequoia_1_1unit__testing_1_1broken__equality.html',1,'sequoia::unit_testing']]],
  ['broken_5finequality',['broken_inequality',['../structsequoia_1_1unit__testing_1_1broken__inequality.html',1,'sequoia::unit_testing']]],
  ['broken_5fmove',['broken_move',['../structsequoia_1_1unit__testing_1_1broken__move.html',1,'sequoia::unit_testing']]],
  ['broken_5fmove_5falloc',['broken_move_alloc',['../structsequoia_1_1unit__testing_1_1broken__move__alloc.html',1,'sequoia::unit_testing']]],
  ['broken_5fmove_5fassignment',['broken_move_assignment',['../structsequoia_1_1unit__testing_1_1broken__move__assignment.html',1,'sequoia::unit_testing']]],
  ['broken_5fswap',['broken_swap',['../structsequoia_1_1unit__testing_1_1broken__swap.html',1,'sequoia::unit_testing']]],
  ['bucketed_5fedge_5fstorage_5ftraits',['bucketed_edge_storage_traits',['../structsequoia_1_1maths_1_1bucketed__edge__storage__traits.html',1,'sequoia::maths']]],
  ['bucketed_5fstorage',['bucketed_storage',['../classsequoia_1_1data__structures_1_1bucketed__storage.html',1,'sequoia::data_structures']]],
  ['bucketed_5fstorage_5ftraits',['bucketed_storage_traits',['../structsequoia_1_1data__structures_1_1bucketed__storage__traits.html',1,'sequoia::data_structures']]]
];
