////////////////////////////////////////////////////////////////////
//                Copyright Oliver J. Rosten 2021.                //
// Distributed under the GNU GENERAL PUBLIC LICENSE, Version 3.0. //
//    (See accompanying file LICENSE.md or copy at                //
//          https://www.gnu.org/licenses/gpl-3.0.en.html)         //
////////////////////////////////////////////////////////////////////

#pragma once

/** \file */

#include "sequoia/TestFramework/RegularTestCore.hpp"
#include "sequoia/Core/Object/Factory.hpp"
#include "sequoia/TestFramework/SumTypeCheckers.hpp"
#include "sequoia/TestFramework/StringCheckers.hpp"
#include "sequoia/TestFramework/ProductTypeCheckers.hpp"

#include <algorithm>
#include <format>
#include <map>
#include <ranges>

namespace sequoia::testing
{
  /** Both factories are equal when they map the same names to the same products, and both report
      their names the same way, so the arm which says so is written once.
   */

  template<test_mode Mode, class Factory>
  void check_factory_names(test_logger<Mode>& logger, const Factory& actual, const Factory& prediction)
  {
    check(equality, "Names", logger, actual.begin_names(), actual.end_names(), prediction.begin_names(), prediction.end_names());
  }

  /** Both factories make a product by name, so the arm which checks a prediction is written once. The
      names are compared first, so that a product is made only by a name the factory knows, and each
      product is checked only once the names agree.
   */

  template<test_mode Mode, class Factory, std::size_t N, class... Args>
  void check_factory_products(test_logger<Mode>& logger,
                              const Factory& actual,
                              const std::array<std::pair<std::string, typename Factory::vessel>, N>& prediction,
                              const Args&... args)
  {
    const auto predictedNames{
      [&prediction](){
        auto names{prediction | std::views::keys | std::ranges::to<std::vector<std::string>>()};
        std::ranges::sort(names);
        return names;
      }()
    };

    const auto actualNames{
      [&actual](){
        std::vector<std::string> names{};
        for(auto i{actual.begin_names()}; i != actual.end_names(); ++i)
        {
          names.push_back(*i);
        }

        return names;
      }()
    };

    if(check(equality, "Names", logger, actualNames, predictedNames))
    {
      for(const auto&[name, product] : prediction)
      {
        check(equality, std::format("Product generated by name '{}'", name), logger, actual.make(name, args...), product);
      }
    }
  }

  template<class... Products>
  struct value_tester<sequoia::object::factory<Products...>>
  {
    using type = sequoia::object::factory<Products...>;
    using element = std::pair<std::string, std::variant<Products...>>;

    template<class... Args>
    using factory_check_type = general_equivalence_check_t<std::tuple<Args...>>;
    
    template<test_mode Mode, class... Args>
      requires (initializable_from<Products, Args...> && ... )
    static void test(factory_check_type<Args...> equivChecker,
                     test_logger<Mode>& logger,
                     const type& actual,
                     const std::array<element, sizeof...(Products)>& prediction)
    {
      auto checkProducts{[&](const Args&... args){ check_factory_products(logger, actual, prediction, args...); }};
      std::apply(checkProducts, equivChecker.customizer);
    }

    template<test_mode Mode>
    static void test(equivalence_check_t,
                     test_logger<Mode>& logger,
                     const type& actual,
                     const std::array<element, sizeof...(Products)>& prediction)
    {
      check_factory_products(logger, actual, prediction);
    }

    template<test_mode Mode>
    static void test(equality_check_t, test_logger<Mode>& logger, const type& actual, const type& prediction)
    {
      check_factory_names(logger, actual, prediction);
    }
  };

  template<class Vessel, class... Args>
  struct value_tester<sequoia::object::erasing_factory<Vessel, Args...>>
  {
    using type = sequoia::object::erasing_factory<Vessel, Args...>;
    using element = std::pair<std::string, Vessel>;

    using factory_check_type = general_equivalence_check_t<std::tuple<Args...>>;

    template<test_mode Mode, std::size_t N>
    static void test(factory_check_type equivChecker,
                     test_logger<Mode>& logger,
                     const type& actual,
                     const std::array<element, N>& prediction)
    {
      auto checkProducts{[&](const Args&... args){ check_factory_products(logger, actual, prediction, args...); }};
      std::apply(checkProducts, equivChecker.customizer);
    }

    template<test_mode Mode, std::size_t N>
      requires (sizeof...(Args) == 0)
    static void test(equivalence_check_t,
                     test_logger<Mode>& logger,
                     const type& actual,
                     const std::array<element, N>& prediction)
    {
      check_factory_products(logger, actual, prediction);
    }

    template<test_mode Mode>
    static void test(equality_check_t, test_logger<Mode>& logger, const type& actual, const type& prediction)
    {
      check_factory_names(logger, actual, prediction);
    }
  };
}
