name: scratch-matrix-called
on:
  workflow_call:
jobs:
  build-and-test:
    if: false
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include: ${{ fromJSON('[{"name":"Gamma"},{"name":"Delta"}]') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo never
